tupla1 = (20, 30, 40, 50, 60)
print(tupla1)
tupla2 = 70, 80, 90, 100, 110
print(tupla2)
tupla3 =  ()
print(tupla3)
tupla4 = tuple("Teste")
print(tupla4)
valor_unico = (3,)
print(valor_unico)
type(valor_unico)
nao_tupla = (3)
type(nao_tupla)
p = ('a', 'b', 'c', 'd', 'e')
print(p)
print(p[0])
print(p[0:3])

p = dict()
print(p)
type(p)
p = {'Nome': 'Paulo', 'Sobrenome': 'Martins', 'Idade': 15}
print(p)
print(p['Nome'])
print(p['Sobrenome'])
idade = p.get('Idade')
print(idade)
p['Sexo'] = 'masculino'
print(p)
p.pop('Sexo')
print(p)
p.keys()
p.values()
p.itens()
